In [1]:
import pandas as pd   # 판다스는 pandas 라이브러리를 임포트해야 사용가능, 보통 pd라는 약자(별칭) 사용

In [ ]:
pd.DataFrame()

In [3]:
df = pd.DataFrame()
print(type(df))

<class 'pandas.core.frame.DataFrame'>

- DataFrame 은 2차원 테이블이고, 테이블의 한 줄(행/열)을 Series 라고 함
- Series 의 모임이 곧, DataFrame이 됨

In [4]:
from numpy import NaN
# Series는
pd.Series([1, 3, 5, NaN, 6, 8 ])

0    1.0
1    3.0
2    5.0
3    NaN
4    6.0
5    8.0
dtype: float64

In [6]:
stu_list = [['Michael', 'John', 'Jennie', 'Susan'],[19, 18, 17, 16]]
print(stu_list)

[['Michael', 'John', 'Jennie', 'Susan'], [19, 18, 17, 16]]

In [7]:
print(type(stu_list))

<class 'list'>

In [9]:
df = pd.DataFrame(stu_list)
df

         0     1       2      3
0  Michael  John  Jennie  Susan
1       19    18      17     16

In [10]:
print(type(df))

<class 'pandas.core.frame.DataFrame'>

In [18]:
# 데이터프레임의 로우과 컬럼을 바꿈
df = df.T

In [19]:
df

         0     1       2      3
0  Michael  John  Jennie  Susan
1       19    18      17     16

In [20]:
df = df.T
df

         0   1
0  Michael  19
1     John  18
2   Jennie  17
3    Susan  16

In [21]:
columns_name = ['name','age']
df.columns = columns_name
df

      name age
0  Michael  19
1     John  18
2   Jennie  17
3    Susan  16