In [2]:
dic_prd = {
    'L' : [5141, 5365, 5084],
    'M' : [4968, 4977, 4915],
    'S' : [5012, 4991, 5029],
    'XL' : [5071, 4976, 5023],
    'XS' : [5195, 4954, 5088]
}
print(dic_prd)
print(type(dic_prd))

{'L': [5141, 5365, 5084], 'M': [4968, 4977, 4915], 'S': [5012, 4991, 5029], 'XL': [5071, 4976, 5023], 'XS': [5195, 4954, 5088]}
<class 'dict'>

In [7]:
import pandas as pd

agg_prd_df = pd.DataFrame(dic_prd, index=['Jacket','Shirt','Trousers'])
agg_prd_df

             L     M     S    XL    XS
Jacket    5141  4968  5012  5071  5195
Shirt     5365  4977  4991  4976  4954
Trousers  5084  4915  5029  5023  5088

In [8]:
agg_prd_df['M']

Jacket      4968
Shirt       4977
Trousers    4915
Name: M, dtype: int64

In [10]:
agg_prd_df[['L','XL']]

             L    XL
Jacket    5141  5071
Shirt     5365  4976
Trousers  5084  5023

In [12]:
# XL, L, M, S, XS 순서로 출력
agg_prd_df[['XL','L','M','S','XS']]

            XL     L     M     S    XS
Jacket    5071  5141  4968  5012  5195
Shirt     4976  5365  4977  4991  4954
Trousers  5023  5084  4915  5029  5088

In [13]:
agg_prd_df

             L     M     S    XL    XS
Jacket    5141  4968  5012  5071  5195
Shirt     5365  4977  4991  4976  4954
Trousers  5084  4915  5029  5023  5088

In [16]:
agg_prd_df['M']['Jacket']

4968

In [17]:
agg_prd_df['S']

Jacket      5012
Shirt       4991
Trousers    5029
Name: S, dtype: int64

In [18]:
agg_prd_df['S'] >= 5000

Jacket       True
Shirt       False
Trousers     True
Name: S, dtype: bool

In [19]:
agg_prd_df

             L     M     S    XL    XS
Jacket    5141  4968  5012  5071  5195
Shirt     5365  4977  4991  4976  4954
Trousers  5084  4915  5029  5023  5088

In [22]:
agg_prd_df[agg_prd_df['S'] >= 5000]['S']['Jacket']

5012

In [42]:
# 12 * 4  행렬에 1부터 48까지의 숫자를 원소로 가지고,  # numpy, np.arange(1,49), reshape()
# index는 0부터 시작하고,
# column은 순서대로 X1, X2, X3, X4 로 하는 
# DataFrame 생성하시오.
import numpy as np
df = pd.DataFrame(data=np.arange(1, 49).reshape(12, 4),
                  index=np.arange(12),
                  columns=["X1","X2","X3","X4"])
df

    X1  X2  X3  X4
0    1   2   3   4
1    5   6   7   8
2    9  10  11  12
3   13  14  15  16
4   17  18  19  20
5   21  22  23  24
6   25  26  27  28
7   29  30  31  32
8   33  34  35  36
9   37  38  39  40
10  41  42  43  44
11  45  46  47  48

In [43]:
# dataframe index
df.index

Int64Index([0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11], dtype='int64')

In [44]:
# dataframe columns
df.columns

Index(['X1', 'X2', 'X3', 'X4'], dtype='object')

In [45]:
# dataframe values
df.values

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16],
       [17, 18, 19, 20],
       [21, 22, 23, 24],
       [25, 26, 27, 28],
       [29, 30, 31, 32],
       [33, 34, 35, 36],
       [37, 38, 39, 40],
       [41, 42, 43, 44],
       [45, 46, 47, 48]])

In [46]:
# 특정 column을 가져오시오.
df["X2"]          # dictionary like

0      2
1      6
2     10
3     14
4     18
5     22
6     26
7     30
8     34
9     38
10    42
11    46
Name: X2, dtype: int64

In [48]:
#  X1 column 에 2 더하기
df["X1"]+2
# df["X1"] = df["X1"]+2  >> 바뀐 데이터 저장하고 싶은 경우

0      3
1      7
2     11
3     15
4     19
5     23
6     27
7     31
8     35
9     39
10    43
11    47
Name: X1, dtype: int64

In [49]:
df.values

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16],
       [17, 18, 19, 20],
       [21, 22, 23, 24],
       [25, 26, 27, 28],
       [29, 30, 31, 32],
       [33, 34, 35, 36],
       [37, 38, 39, 40],
       [41, 42, 43, 44],
       [45, 46, 47, 48]])

In [50]:
df.head()

   X1  X2  X3  X4
0   1   2   3   4
1   5   6   7   8
2   9  10  11  12
3  13  14  15  16
4  17  18  19  20

In [51]:
df.tail()

    X1  X2  X3  X4
7   29  30  31  32
8   33  34  35  36
9   37  38  39  40
10  41  42  43  44
11  45  46  47  48

In [52]:
df.info() # dataframe 에 대한 요약 정보

<class 'pandas.core.frame.DataFrame'>
Int64Index: 12 entries, 0 to 11
Data columns (total 4 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   X1      12 non-null     int64
 1   X2      12 non-null     int64
 2   X3      12 non-null     int64
 3   X4      12 non-null     int64
dtypes: int64(4)
memory usage: 480.0 bytes

In [53]:
df.describe()   # dataframe 에 대한 전체적인 통계정보를 보여줌

              X1         X2         X3         X4
count  12.000000  12.000000  12.000000  12.000000
mean   23.000000  24.000000  25.000000  26.000000
std    14.422205  14.422205  14.422205  14.422205
min     1.000000   2.000000   3.000000   4.000000
25%    12.000000  13.000000  14.000000  15.000000
50%    23.000000  24.000000  25.000000  26.000000
75%    34.000000  35.000000  36.000000  37.000000
max    45.000000  46.000000  47.000000  48.000000

In [58]:
# X2 column 을 기준으로 내림차순 정렬하시오.
df.sort_values(by="X2", ascending=False)

    X1  X2  X3  X4
11  45  46  47  48
10  41  42  43  44
9   37  38  39  40
8   33  34  35  36
7   29  30  31  32
6   25  26  27  28
5   21  22  23  24
4   17  18  19  20
3   13  14  15  16
2    9  10  11  12
1    5   6   7   8
0    1   2   3   4

In [59]:
df

    X1  X2  X3  X4
0    1   2   3   4
1    5   6   7   8
2    9  10  11  12
3   13  14  15  16
4   17  18  19  20
5   21  22  23  24
6   25  26  27  28
7   29  30  31  32
8   33  34  35  36
9   37  38  39  40
10  41  42  43  44
11  45  46  47  48

## Fancy indexing
- 데이터를 filtering
- 전체 데이터에서 원하는 일부의 데이터를 찾아오는 방법

In [62]:
# df["X1"]
df.X1

0      1
1      5
2      9
3     13
4     17
5     21
6     25
7     29
8     33
9     37
10    41
11    45
Name: X1, dtype: int64

In [68]:
# df에서 index value를 기준으로 indexing도 가능함
# df.index[0]
df.loc[0]

X1    1
X2    2
X3    3
X4    4
Name: 0, dtype: int64

In [64]:
df

    X1  X2  X3  X4
0    1   2   3   4
1    5   6   7   8
2    9  10  11  12
3   13  14  15  16
4   17  18  19  20
5   21  22  23  24
6   25  26  27  28
7   29  30  31  32
8   33  34  35  36
9   37  38  39  40
10  41  42  43  44
11  45  46  47  48

In [69]:
# df.loc 는 특정값을 기준으로 indexing 함
df.loc[7]

X1    29
X2    30
X3    31
X4    32
Name: 7, dtype: int64

In [76]:
# df.loc에 2차원 indexing도 가능함
# df.loc[9, "X4"]
# df.loc[3:5, "X2":"X4"]
df.loc[[0,1,4,6,10],["X1","X3"]]

    X1  X3
0    1   3
1    5   7
4   17  19
6   25  27
10  41  43

In [77]:
# 2차원 리스트 indexing 과 같은 원리
# integer- location based indexting
df.iloc[5]

X1    21
X2    22
X3    23
X4    24
Name: 5, dtype: int64

In [78]:
# iloc 로 2차원 indexing 
# row 기준으로 index 3,4 를 가져오고, column 기준으로 0,1 을 가져옴
df.iloc[[3,4], [0,1]]

   X1  X2
3  13  14
4  17  18